name: polo0.2.1
channels:
  - defaults
  - conda-forge
dependencies:
  - tensorflow
  - pyinstaller
  - ca-certificates
  - certifi
  - openssl
  - pyqt=5.15
  - jinja2
  - python-pptx
  - matplotlib
  - pip
  - pip:
    - molmass
