# Windows environment.yml
# Set up .condarc:
# conda config --add channels conda-forge
# conda config --set channel_priority strict
name: polo0.2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12 # Recommended version for TensorFlow 2.18.1
  - pyinstaller
  - ca-certificates
  - certifi
  - openssl
  - pyqt=5.15
  - jinja2
  - python-pptx
  - matplotlib
  - pip
  - pip:
    - molmass
    # Pip packages for TensorFlow is the recommended way to install TensorFlow.
    - tensorflow
