# X64 macOS: Use this environment file to create a conda environment for running PoLo on Intel-based Macs.
# Set up .condarc:
# conda config --add channels conda-forge
# conda config --set channel_priority strict
name: polo0.2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyinstaller
  - ca-certificates
  - certifi
  - openssl
  - pyqt=5.15
  - jinja2
  - python-pptx
  - matplotlib
  - pip
  - pip:
    - molmass
    # Pip packages for TensorFlow is the recommended way to install TensorFlow.
    - tensorflow # CPU only; version 2.16.2: the last release to support macOS x86. Supports older NVIDIA GPUs (compute capability 5.0).
