name: polo0.2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyinstaller
  - ca-certificates
  - certifi
  - openssl
  - pyqt=5.15
  - jinja2
  - python-pptx
  - matplotlib
  - pip
  - pip:
    - molmass
    - tensorflow==2.18.1
    - tensorflow-metal
